2025-06-27 15:10:36> 已从配置加载: 2 个虚拟目录
2025-06-27 15:10:38> 服务器已启动: http://0.0.0.0:8000
2025-06-27 15:10:38> 服务器启动(多线程模式): http://0.0.0.0:8000
2025-06-27 15:10:38> 根目录: C:/Users/Administrator/Desktop/python-pro
2025-06-27 15:10:45> 192.168.100.4:51301- "GET /download HTTP/1.1" 200 -
2025-06-27 15:10:45> 192.168.100.4:51302- "GET /favicon.ico HTTP/1.1" 200 -
2025-06-27 15:10:46> 192.168.100.4:51302- "GET / HTTP/1.1" 200 -
2025-06-27 15:10:48> 192.168.100.4:51302- "GET /login HTTP/1.1" 200 -
2025-06-27 15:10:49> 192.168.100.4:51310- "POST /login HTTP/1.1" 302 -
2025-06-27 15:10:49> 192.168.100.4:51310- 用户认证成功，用户名admin,session:06559536eb756e70a45d1dcb1da5e4a6
2025-06-27 15:10:49> 192.168.100.4:51317- "GET / HTTP/1.1" 200 -
2025-06-27 15:10:56> 192.168.100.4:51318- code 500, message Upload processing failed: cannot access local variable 'target_path' where it is not associated with a value
2025-06-27 15:10:56> 192.168.100.4:51318- "POST /upload HTTP/1.1" 500 -
